03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SET TIME_ZONE[*] = '+00:00' "; erwartet "@, AUTOCOMMIT, MVCC, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, COMPRESS_LOB, DATABASE, COLLATION, BINARY_COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, CREATE, HSQLDB.DEFAULT_TABLE_TYPE, PAGE_STORE, CACHE_TYPE, FILE_LOCK, DB_CLOSE_ON_EXIT, AUTO_SERVER, AUTO_SERVER_PORT, AUTO_RECONNECT, ASSERT, ACCESS_MODE_DATA, OPEN_NEW, JMX, PAGE_SIZE, RECOVER, NAMES, SCHEMA, DATESTYLE, SEARCH_PATH, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, LOGSIZE, FOREIGN_KEY_CHECKS"
Syntax error in SQL statement "SET TIME_ZONE[*] = '+00:00' "; expected "@, AUTOCOMMIT, MVCC, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, COMPRESS_LOB, DATABASE, COLLATION, BINARY_COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, CREATE, HSQLDB.DEFAULT_TABLE_TYPE, PAGE_STORE, CACHE_TYPE, FILE_LOCK, DB_CLOSE_ON_EXIT, AUTO_SERVER, AUTO_SERVER_PORT, AUTO_RECONNECT, ASSERT, ACCESS_MODE_DATA, OPEN_NEW, JMX, PAGE_SIZE, RECOVER, NAMES, SCHEMA, DATESTYLE, SEARCH_PATH, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, LOGSIZE, FOREIGN_KEY_CHECKS"; SQL statement:
SET time_zone = '+00:00' [42001-175]
03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SET SQL_MODE[*] = 'NO_AUTO_VALUE_ON_ZERO' "; erwartet "@, AUTOCOMMIT, MVCC, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, COMPRESS_LOB, DATABASE, COLLATION, BINARY_COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, CREATE, HSQLDB.DEFAULT_TABLE_TYPE, PAGE_STORE, CACHE_TYPE, FILE_LOCK, DB_CLOSE_ON_EXIT, AUTO_SERVER, AUTO_SERVER_PORT, AUTO_RECONNECT, ASSERT, ACCESS_MODE_DATA, OPEN_NEW, JMX, PAGE_SIZE, RECOVER, NAMES, SCHEMA, DATESTYLE, SEARCH_PATH, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, LOGSIZE, FOREIGN_KEY_CHECKS"
Syntax error in SQL statement "SET SQL_MODE[*] = 'NO_AUTO_VALUE_ON_ZERO' "; expected "@, AUTOCOMMIT, MVCC, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, COMPRESS_LOB, DATABASE, COLLATION, BINARY_COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, CREATE, HSQLDB.DEFAULT_TABLE_TYPE, PAGE_STORE, CACHE_TYPE, FILE_LOCK, DB_CLOSE_ON_EXIT, AUTO_SERVER, AUTO_SERVER_PORT, AUTO_RECONNECT, ASSERT, ACCESS_MODE_DATA, OPEN_NEW, JMX, PAGE_SIZE, RECOVER, NAMES, SCHEMA, DATESTYLE, SEARCH_PATH, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, LOGSIZE, FOREIGN_KEY_CHECKS"; SQL statement:
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO' [42001-175]
03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Bedingung "BUSINESS_OBJECT_ATTRIBUTE" besteht bereits
Constraint "BUSINESS_OBJECT_ATTRIBUTE" already exists; SQL statement:
CREATE TABLE `business_object_attributes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `business_object` int(11) NOT NULL,
  `attribute` int(11) NOT NULL,
  `order` int(9) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `business_object_attribute` (`business_object`,`attribute`),
  UNIQUE KEY `business_object_order` (`business_object`,`order`),
  KEY `attribute` (`attribute`),
  CONSTRAINT `business_object_attributes_ibfk_1` FOREIGN KEY (`business_object`) REFERENCES `business_objects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `business_object_attributes_ibfk_2` FOREIGN KEY (`attribute`) REFERENCES `attributes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [90045-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:96)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:70)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:169)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:745)
03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "BUSINESS_OBJECT_ATTRIBUTES" nicht gefunden
Table "BUSINESS_OBJECT_ATTRIBUTES" not found; SQL statement:
INSERT INTO `business_object_attributes` (`id`, `business_object`, `attribute`, `order`) VALUES
(1,	1,	1,	0),
(2,	1,	2,	1),
(3,	1,	3,	2),
(4,	1,	4,	3),
(5,	2,	5,	0),
(6,	2,	6,	1),
(7,	2,	1,	2),
(8,	2,	7,	3),
(9,	2,	8,	4),
(10,	2,	9,	5),
(11,	2,	10,	6),
(12,	2,	11,	7),
(13,	3,	12,	0),
(14,	3,	13,	1),
(15,	3,	14,	2),
(16,	3,	15,	3),
(17,	3,	16,	4),
(18,	3,	17,	5),
(19,	3,	49,	6),
(20,	4,	18,	0),
(21,	4,	19,	1),
(22,	4,	20,	2),
(23,	4,	21,	3),
(24,	4,	22,	4),
(25,	4,	23,	5),
(26,	4,	24,	6),
(27,	4,	25,	7),
(28,	4,	26,	8),
(31,	4,	27,	9),
(32,	4,	28,	10),
(34,	4,	29,	11),
(36,	4,	30,	12),
(37,	4,	31,	13),
(38,	4,	32,	14),
(39,	4,	33,	15),
(40,	5,	34,	0),
(41,	5,	35,	1),
(42,	5,	36,	2),
(43,	5,	37,	3),
(44,	5,	38,	4),
(45,	5,	39,	5),
(46,	5,	40,	6),
(47,	6,	20,	0),
(48,	6,	1,	1),
(49,	6,	6,	2),
(50,	6,	5,	3),
(51,	6,	41,	4),
(52,	7,	42,	0),
(53,	7,	44,	1),
(54,	7,	43,	2),
(55,	7,	31,	3),
(56,	7,	12,	4),
(57,	7,	45,	5),
(58,	8,	49,	0),
(59,	9,	46,	0),
(60,	9,	6,	1),
(61,	9,	5,	2),
(62,	9,	1,	3),
(63,	9,	7,	4),
(64,	9,	8,	5),
(65,	9,	9,	6),
(66,	9,	10,	7),
(67,	9,	11,	8),
(68,	10,	50,	0),
(69,	10,	51,	1),
(70,	10,	52,	2),
(71,	10,	53,	3),
(72,	10,	54,	4),
(73,	10,	55,	5),
(74,	10,	56,	6),
(75,	10,	57,	7),
(76,	10,	35,	8),
(77,	10,	15,	9),
(78,	10,	58,	10),
(80,	10,	59,	11),
(81,	10,	60,	12),
(82,	10,	61,	13),
(83,	11,	20,	0),
(84,	11,	6,	1),
(85,	11,	5,	2),
(86,	11,	7,	3),
(87,	11,	8,	4),
(88,	11,	9,	5),
(89,	11,	10,	6),
(90,	11,	11,	7),
(91,	12,	62,	0),
(92,	12,	63,	1),
(93,	12,	64,	2),
(94,	12,	65,	3) [42102-175]
03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "CREATE TABLE ""USERS"" (
  ""ID"" INT(11) NOT NULL AUTO_INCREMENT,
  ""MAIL"" VARCHAR(255) NOT NULL,
  ""NAME"" VARCHAR(255) NOT NULL,
  ""PASSWD"" VARCHAR(255) NOT NULL,
  ""TIME"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (""ID""),
  UNIQUE KEY ""MAIL"" (""MAIL"")
) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; erwartet "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ""USERS"" (
  ""ID"" INT(11) NOT NULL AUTO_INCREMENT,
  ""MAIL"" VARCHAR(255) NOT NULL,
  ""NAME"" VARCHAR(255) NOT NULL,
  ""PASSWD"" VARCHAR(255) NOT NULL,
  ""TIME"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (""ID""),
  UNIQUE KEY ""MAIL"" (""MAIL"")
) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; expected "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mail` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `passwd` varchar(255) NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mail` (`mail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [42001-175]
03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "CREATE TABLE ""USER_PROCESS_INSTANCES"" (
  ""ID"" INT(11) NOT NULL AUTO_INCREMENT,
  ""USER"" INT(11) NOT NULL,
  ""PROCESS"" VARCHAR(255) NOT NULL,
  ""TIME"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (""ID""),
  UNIQUE KEY ""USER_PROCESS"" (""USER"",""PROCESS""),
  CONSTRAINT ""USER_PROCESS_INSTANCES_IBFK_1"" FOREIGN KEY (""USER"") REFERENCES ""USERS"" (""ID"") ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; erwartet "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ""USER_PROCESS_INSTANCES"" (
  ""ID"" INT(11) NOT NULL AUTO_INCREMENT,
  ""USER"" INT(11) NOT NULL,
  ""PROCESS"" VARCHAR(255) NOT NULL,
  ""TIME"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (""ID""),
  UNIQUE KEY ""USER_PROCESS"" (""USER"",""PROCESS""),
  CONSTRAINT ""USER_PROCESS_INSTANCES_IBFK_1"" FOREIGN KEY (""USER"") REFERENCES ""USERS"" (""ID"") ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; expected "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE `user_process_instances` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` int(11) NOT NULL,
  `process` varchar(255) NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_process` (`user`,`process`),
  CONSTRAINT `user_process_instances_ibfk_1` FOREIGN KEY (`user`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [42001-175]
03-04 22:16:01 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "CREATE TABLE ""USER_SESSIONS"" (
  ""ID"" INT(11) NOT NULL AUTO_INCREMENT,
  ""USER"" INT(11) NOT NULL,
  ""KEY"" VARCHAR(255) NOT NULL,
  ""TOKEN"" VARCHAR(255) NOT NULL,
  ""TIME"" TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  ""UPDATE"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (""ID""),
  KEY ""USER"" (""USER""),
  CONSTRAINT ""USER_SESSIONS_IBFK_1"" FOREIGN KEY (""USER"") REFERENCES ""USERS"" (""ID"") ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; erwartet "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ""USER_SESSIONS"" (
  ""ID"" INT(11) NOT NULL AUTO_INCREMENT,
  ""USER"" INT(11) NOT NULL,
  ""KEY"" VARCHAR(255) NOT NULL,
  ""TOKEN"" VARCHAR(255) NOT NULL,
  ""TIME"" TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  ""UPDATE"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (""ID""),
  KEY ""USER"" (""USER""),
  CONSTRAINT ""USER_SESSIONS_IBFK_1"" FOREIGN KEY (""USER"") REFERENCES ""USERS"" (""ID"") ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; expected "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE `user_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` int(11) NOT NULL,
  `key` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user` (`user`),
  CONSTRAINT `user_sessions_ibfk_1` FOREIGN KEY (`user`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [42001-175]
03-04 23:07:08 jdbc[40]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "USER" nicht gefunden
Table "USER" not found; SQL statement:
SELECT * FROM `user` WHERE `email` = 'email' [42102-175]
03-04 23:08:07 jdbc[47]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "USER" nicht gefunden
Table "USER" not found; SQL statement:
SELECT * FROM `user` WHERE `email` = 'email' [42102-175]
03-04 23:15:33 jdbc[54]: exception
org.h2.jdbc.JdbcSQLException: Feld "EMAIL" nicht gefunden
Column "EMAIL" not found; SQL statement:
SELECT * FROM `users` WHERE `email` = 'email' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.command.dml.Select.prepare(Select.java:813)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:72)
	at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:464)
	at models.util.db.DBHandler.exec(DBHandler.java:272)
	at models.util.db.DBHandler.select(DBHandler.java:94)
	at models.util.sessions.User.init(User.java:73)
	at controllers.AuthController.login(AuthController.java:52)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:96)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:96)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
03-04 23:17:03 jdbc[54]: exception
org.h2.jdbc.JdbcSQLException: Feld "EMAIL" nicht gefunden
Column "EMAIL" not found; SQL statement:
SELECT * FROM `users` WHERE `email` = 'email' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.command.dml.Select.prepare(Select.java:813)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:72)
	at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:464)
	at models.util.db.DBHandler.exec(DBHandler.java:272)
	at models.util.db.DBHandler.select(DBHandler.java:94)
	at models.util.sessions.User.init(User.java:73)
	at controllers.AuthController.login(AuthController.java:52)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:96)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:96)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
03-04 23:22:46 jdbc[64]: exception
org.h2.jdbc.JdbcSQLException: Funktion "SHA1" nicht gefunden
Function "SHA1" not found; SQL statement:
INSERT INTO users(mail, name, passwd) VALUES('maedche@uni-mannheim.de', 'Alexander Mädche', sha1('test123')) [90022-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.Parser.readJavaFunction(Parser.java:2254)
	at org.h2.command.Parser.readFunction(Parser.java:2306)
	at org.h2.command.Parser.readTerm(Parser.java:2625)
	at org.h2.command.Parser.readFactor(Parser.java:2178)
	at org.h2.command.Parser.readSum(Parser.java:2165)
	at org.h2.command.Parser.readConcat(Parser.java:2138)
	at org.h2.command.Parser.readCondition(Parser.java:2003)
	at org.h2.command.Parser.readAnd(Parser.java:1976)
	at org.h2.command.Parser.readExpression(Parser.java:1968)
	at org.h2.command.Parser.parseInsert(Parser.java:1026)
	at org.h2.command.Parser.parsePrepared(Parser.java:394)
	at org.h2.command.Parser.parse(Parser.java:298)
	at org.h2.command.Parser.parse(Parser.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
03-04 23:24:07 jdbc[64]: exception
org.h2.jdbc.JdbcSQLException: Funktion "SHA1" nicht gefunden
Function "SHA1" not found; SQL statement:
INSERT INTO users(mail, name, passwd) VALUES('maedche@uni-mannheim.de', 'Alexander Mädche', sha1('test123')) [90022-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.Parser.readJavaFunction(Parser.java:2254)
	at org.h2.command.Parser.readFunction(Parser.java:2306)
	at org.h2.command.Parser.readTerm(Parser.java:2625)
	at org.h2.command.Parser.readFactor(Parser.java:2178)
	at org.h2.command.Parser.readSum(Parser.java:2165)
	at org.h2.command.Parser.readConcat(Parser.java:2138)
	at org.h2.command.Parser.readCondition(Parser.java:2003)
	at org.h2.command.Parser.readAnd(Parser.java:1976)
	at org.h2.command.Parser.readExpression(Parser.java:1968)
	at org.h2.command.Parser.parseInsert(Parser.java:1026)
	at org.h2.command.Parser.parsePrepared(Parser.java:394)
	at org.h2.command.Parser.parse(Parser.java:298)
	at org.h2.command.Parser.parse(Parser.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
03-04 23:24:37 jdbc[69]: exception
org.h2.jdbc.JdbcSQLException: Datenumwandlungsfehler beim Umwandeln von "'ba3be039' (USER_SESSIONS: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F08AE3F5_B8BE_4CD3_888C_CD34E346CBAF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F08AE3F5_B8BE_4CD3_888C_CD34E346CBAF)"
Data conversion error converting "'ba3be039' (USER_SESSIONS: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F08AE3F5_B8BE_4CD3_888C_CD34E346CBAF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F08AE3F5_B8BE_4CD3_888C_CD34E346CBAF)"; SQL statement:
INSERT INTO `user_sessions` (`id`, `user`, `key`, `time`, `update`) VALUES ('ba3be039', '1', '258f9f678a01a06dfae7d7ebb242d71dcb051a85', 'null', 'null') -- ('ba3be039', '1', '258f9f678a01a06dfae7d7ebb242d71dcb051a85', 'null', 'null') [22018-175]
